In [2]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
b = np.array([[1,2,3],[3,4,6]])
b

array([[1, 2, 3],
       [3, 4, 6]])

In [ ]:
# shape
print(a.shape,b.shape)

(4,) (2, 3)


In [11]:
# reshape
c = a.reshape((4,1))
c.shape

(4, 1)

In [13]:
d = a.reshape(2,2,1)
d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [15]:
d = a.reshape(2,-1,1)
d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [20]:
# concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [21]:
d = a*b
d

array([ 4, 10, 18])

In [22]:
e = np.array([7])
f = a*e
f

array([ 7, 14, 21])

In [31]:
# slicing
a = np.array([1,2,3,4,5,6,7,8])
b = a[2:6]
print(b)
b = a[::2]
print(b)
b = a[a%2==0]
print(b)

[3 4 5 6]
[1 3 5 7]
[2 4 6 8]


In [33]:
sum_a = np.sum(a)
print(sum_a)
max_a = np.max(a)
print(max_a)
a = np.array([4,5,3,1,7,6,9])
b = np.sort(a)
print(b)


36
8
[1 3 4 5 6 7 9]


In [35]:
a = np.random.randint(-100,50,(3,5))
a

array([[ -2, -28,  44, -45, -80],
       [-94,   4, -98, -21,  13],
       [-64,  27, -98,  21, -40]], dtype=int32)

In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c)
c = np.hstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [39]:
# normalize
mean_a = np.mean(a)
print(mean_a)
std_a = np.std(a)
print(std_a)
norm_a = (a - mean_a) / std_a
print(norm_a)
print(np.std(norm_a))
print(np.mean(norm_a))

2.0
0.816496580927726
[-1.22474487  0.          1.22474487]
0.9999999999999999
0.0
